use customer_behaviour;

select * from customer;
desc table customer;
CREATE TABLE customers (
    customer_id INT,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount DECIMAL(10,2),
    location VARCHAR(100),
    size VARCHAR(10),
    color VARCHAR(30),
    season VARCHAR(20),
    review_rating DECIMAL(3,1),
    subscription_status VARCHAR(5),
    shipping_type VARCHAR(30),
    discount_applied VARCHAR(5),
    previous_purchases INT,
    payment_method VARCHAR(30),
    frequency_of_purchases VARCHAR(30),
    age_group VARCHAR(30),
    purchase_frequency_days INT
);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/customer_behavior_clean.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
desc table customers;
-- Q1 = what is total revenue generated by male or female customers?
select gender,sum(purchase_amount) as revenue from customers group by gender;  

-- 	Q2 = which customers used a discount but still spent more than average purchase amonut?
select customer_id,purchase_amount from customers where discount_applied='yes' and purchase_amount>=(select avg(purchase_amount) from customer);

-- Q3 = which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as "Average product rating" from customers group by item_purchased order by avg(review_rating) desc limit 5;

-- Q4= Compare the average Purchase amounts between standard and express shipping.
select shipping_type,round(avg(purchase_amount),2) from customer where shipping_type in ('Standard','Express') group by shipping_type;

-- Q5= Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend,round(sum(purchase_amount),2) as total_revenue
from customers group by subscription_status order by total_revenue, avg_spend desc;

-- Q6= Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased, round(sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*) * 100.0,2) as discount_rate from customers group by item_purchased order by discount_rate desc limit 5;

-- Q7= segment customers into new, returning, and loyal based on their total number of prevous purchases, and show the count of each segment.
with customer_type as (select customer_id,previous_purchases, case when previous_purchases=1 then 'New' when previous_purchases between 2 and 10 then 'Returning' else 'loyal' end as customer_segment from customers) select customer_segment,count(*) as "numbers of customers"
from customer_type group by customer_segment;

-- Q8= what are the top 3 most purchased products within each category?
with item_counts as (select category,item_purchased ,count(customer_id) as total_orders ,row_number() over (Partition by category order by count(customer_id)desc) as item_rank from customer group by category, item_purchased) 
select item_rank, category,item_purchased,total_orders from item_counts where item_rank<=3;

-- Q9= Are customers who are repeat buyers (more than 5 prevoius purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from customers where previous_purchases>5 group by subscription_status;

-- Q10 = what is revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue from customers group by age_group order by total_revenue desc;